
stages:
  - build
  - deploy

build:darwin:
  stage: build
  tags:
    - darwin
  script:
    - scripts/ci-build.sh
  artifacts:
    paths:
      - binaries

deploy:
  stage: deploy
  tags:
    - dropsy
  script:
    - scripts/ci-deploy.sh
  dependencies:
    - :build:darwin

